name: jobscript-env

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - bedtools
  - seaborn
  - art=2016.06.05
  - ivar
  - minimap2
  - samtools
  - seqtk
  - seqkit
  - bcftools>=1.15
